dist: focal
sudo: required
services:
  - docker

before_install: 
  - docker build -t aadi378/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aadi378/react-test npm test

after_success: 
  - docker build -t aadi378/multi-client ./client
  - docker build -t aadi378/multi-nginx ./nginx
  - docker build -t aadi378/multi-server ./server
  - docker build -t aadi378/multi-worker ./worker
  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push aadi378/multi-client
  - docker push aadi378/multi-nginx
  - docker push aadi378/multi-server
  - docker push aadi378/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-us-east-1-721565904067
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY